myspace/views/blog.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, is_logged_in
from ..forms import PostForm
from ..models import Post

blog = Blueprint('blog', __name__)

# ALL POSTS
@blog.route("")
def all_posts():
  posts = Post.query.all()
  return render_template('blog/blog.html', title="Blog", posts=posts)

# SINGLE POST
@blog.route("/<int:post_id>")
def single_post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template('blog/post-r.html', title=post.title, post=post)

# CREATE POST
@blog.route("/new", methods=['GET', 'POST'])
@is_logged_in
def new_post():
  form = PostForm()
  posts = Post.query.filter_by(user_id=session['username']).all()
  if form.validate_on_submit():
    author = session['username']
    post = Post(title=form.title.data, content=form.content.data,
    user_id=author)
    db.session.add(post)
    db.session.commit()
    flash('Post Created!', 'success')
    return redirect(url_for('.all_posts'))
  return render_template('blog/post-cu.html', title="New Post", form=form, posts=posts)

# UPDATE POST
@blog.route("/<int:post_id>/update", methods=['GET', 'POST'])
@is_logged_in
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.user_id != session['username']:
    abort(403)
  form = PostForm()
  posts = Post.query.filter_by(user_id=session['username']).all()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Post Updated','success')
    return redirect(url_for('.single_post', post_id=post.id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('blog/post-cu.html', title="Update Post", form=form, posts=posts)

# DELETE POST
@blog.route("/<int:post_id>/delete", methods=['POST'])
@is_logged_in
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.user_id != session['username']:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Post Deleted','success')
  return redirect(url_for('.all_posts'))

myspace/templates/blog/blog.html
{% extends 'layout.html' %}

{% block body %}
  
  <h1>Welcome to my Blog!</h1>

  <div id="blogroll">
    {% for post in posts %}
    <article>
      <div class="card">
        <div>
          <h4><a href="{{ url_for('blog.single_post', post_id=post.id) }}">{{ post.title }}</a></h4>
          <div>
            <small>{{ post.user_id }} | {{ post.date_posted.strftime('%d-%m-%Y') }}</small>
          </div>
        </div>
        <div>
          {% if post.content|length < 500 %}
            <p>{{ post.content }}</p>
          {% else %}
            <p>{{ post.content[:500] }} &hellip;</p>
          {% endif %}
        </div>
      </div>
    </article>

    <hr>
    {% endfor %}
  </div>
  

{% endblock body %}

myspace/templates/blog/post-cu.html
{% extends 'sidebar-page.html' %}

{% block main %}

<h3>{{ title }}</h3>

<form method="POST" action="">
  <div>
    {{ form.title.label }}
    {% if form.title.errors %}
      {% for error in form.title.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    {% endif %}
    {{ form.title(class_="u-full-width") }}
  </div>
  <div>
    {{ form.content.label }}
    {{ form.content(class_="u-full-width") }}
  </div>
  <div>
    {{ form.submit(class_="button-primary") }}
  </div>
  {{ form.csrf_token }}
</form>

{% endblock main %}

{% block sidebar %}

  <h3>My Recent Posts</h3>

  {% if posts %}
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Title</th>
        <th>Date Created</th>
      </tr>
    </thead>
    <tbody>
      {% for post in posts %}
      <tr>
        <td><a href="{{ url_for('blog.single_post', post_id=post.id) }}">{{ post.title }}</a></td>
        <td>{{ post.date_posted.strftime('%d-%m-%Y') }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>You haven't written any posts yet!</p>
  {% endif %}

{% endblock sidebar %}

myspace/templates/blog/post-r.html
{% extends 'layout.html' %}

{% block body %}
  
  <article id="post">
    <div>
      <div id="post-header">
        <div>
          <h3>{{ post.title }}</h3>
          <small><em>Written by {{ post.user_id }} on {{ post.date_posted.strftime('%d-%m-%Y') }}</em></small>
        </div>
        
      </div>
      <div class="post-contents">
        <p>{{ post.content }}</p>
      </div>
    </div>
    <hr>
    {% if post.user_id == session['username'] %}
    <div class="post-controls">
      <a href="{{ url_for('blog.update_post', post_id=post.id) }}" class="button">Update</a>
      <form action="{{ url_for('blog.delete_post', post_id=post.id) }}" method="POST">
        <input type="submit" value="delete" class="delete-btn">
      </form>
    </div>
    {% endif %}   
  </article>


{% endblock body %}