myspace/views/blog.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, is_logged_in
from ..forms import PostForm
from ..models import Post

blog = Blueprint('blog', __name__)

# ALL POSTS
@blog.route("")
def all_posts():
  posts = Post.query.all()
  return render_template('blog/blog.html', title="Blog", posts=posts)

# SINGLE POST
@blog.route("/<int:post_id>")
def single_post(post_id):
  post = Post.query.get_or_404(post_id)
  return render_template('blog/post-r.html', title=post.title, post=post)

# CREATE POST
@blog.route("/new", methods=['GET', 'POST'])
@is_logged_in
def new_post():
  form = PostForm()
  posts = Post.query.filter_by(user_id=session['username']).all()
  if form.validate_on_submit():
    author = session['username']
    post = Post(title=form.title.data, content=form.content.data,
    user_id=author)
    db.session.add(post)
    db.session.commit()
    flash('Post Created!', 'success')
    return redirect(url_for('.all_posts'))
  return render_template('blog/post-cu.html', title="New Post", form=form, posts=posts)

# UPDATE POST
@blog.route("/<int:post_id>/update", methods=['GET', 'POST'])
@is_logged_in
def update_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.user_id != session['username']:
    abort(403)
  form = PostForm()
  posts = Post.query.filter_by(user_id=session['username']).all()
  if form.validate_on_submit():
    post.title = form.title.data
    post.content = form.content.data
    db.session.commit()
    flash('Post Updated','success')
    return redirect(url_for('.single_post', post_id=post.id))
  elif request.method == 'GET':
    form.title.data = post.title
    form.content.data = post.content
  return render_template('blog/post-cu.html', title="Update Post", form=form, posts=posts)

# DELETE POST
@blog.route("/<int:post_id>/delete", methods=['POST'])
@is_logged_in
def delete_post(post_id):
  post = Post.query.get_or_404(post_id)
  if post.user_id != session['username']:
    abort(403)
  db.session.delete(post)
  db.session.commit()
  flash('Post Deleted','success')
  return redirect(url_for('.all_posts'))

myspace/views/main.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session

from .. import db, bcrypt, is_logged_in
from ..forms import LoginForm
from ..models import User

main = Blueprint('main', __name__)

@main.route("/")
def landing():
  return render_template('landing-page.html')

@main.route("/home")
def home():
  return render_template('home.html', title="Home")

@main.route("/docs")
def documentation():
  return render_template('docs.html', title="Docs")

# DASHBOARD AREA
@main.route("/admin")
@is_logged_in
def admin():
  return render_template('admin-dashboard.html', title="Admin Area")

# LOGIN
@main.route("/login", methods=['GET', 'POST'])
def login():
  if 'logged_in' in session:
    return redirect(url_for('.admin'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(username=form.username.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      session['logged_in'] = True
      session['username'] = form.username.data
      flash(f"You're now logged in as {form.username.data}", "success")
      return redirect(url_for('.admin'))
    else:
      flash('Login Unsuccessful. Please check username and password', 'error')
  return render_template('login.html', title="Login", form=form)

# LOGOUT
@main.route("/logout")
@is_logged_in
def logout():
  session.clear()
  flash("You've been successfully logged out", 'success')
  return redirect(url_for('.home'))

myspace/views/recipes.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, is_logged_in
from ..forms import RecipeForm
from ..models import Recipe

recipes = Blueprint('recipes', __name__)

# READ ALL RECIPES
@recipes.route("/", methods=['GET'])
def all_recipes():
  recipes = Recipe.query.order_by(Recipe.name).all()
  return render_template('recipes/recipe-book.html', title="My Recipes", recipes=recipes)

# READ ONE RECIPE
@recipes.route("/<string:name>")
def single_recipe(name):
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  return render_template('recipes/recipe-r.html', title=recipe.name, recipe=recipe)

# ADD NEW RECIPE
@recipes.route("/new", methods=['GET', 'POST'])
@is_logged_in
def new_recipe():
  recipes = Recipe.query.order_by(Recipe.name).all()
  form = RecipeForm()
  curr_user = session['username']
  if request.method =='POST':
    if form.validate_on_submit():
      recipe = Recipe(name=form.name.data, ingredients=form.ingredients.data, 
      steps=form.steps.data, stars=form.stars.data, user_name=curr_user)
      db.session.add(recipe)
      db.session.commit()
      flash(f'{form.name.data} recipe created!', 'success')
      return redirect(url_for('.all_recipes'))
    else:
        flash('Invalid Coordintes! Please try again', 'error')
  return render_template('recipes/recipe-cu.html', title="Create Recipe", form=form, curr_user=curr_user, recipes=recipes)

# UPDATE RECIPE
@recipes.route("/<string:name>/update", methods=['GET', 'POST'])
@is_logged_in
def update_recipe(name):
  recipes = Recipe.query.order_by(Recipe.name).all()
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  if recipe.user_name != session['username']:
    abort(403)
  form = RecipeForm()
  if request.method =='POST' and form.validate_on_submit():
    recipe.name = form.name.data
    recipe.ingredients = form.ingredients.data
    recipe.steps = form.steps.data
    recipe.stars = form.stars.data
    db.session.commit()
    flash(f'{form.name.data} recipe updated!','success')
    return redirect(url_for('.all_recipes'))
  elif request.method == 'GET':
    form.name.data = recipe.name
    form.ingredients.data = recipe.ingredients
    form.steps.data = recipe.steps
    form.stars.data = recipe.stars
  return render_template('recipes/recipe-cu.html', title="Update Recipe", form=form, recipes=recipes)

# DELETE RECIPE
@recipes.route("/<string:name>/delete", methods=['POST'])
@is_logged_in
def delete_recipe(name):
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  if recipe.user_name != session['username']:
    abort(403)
  db.session.delete(recipe)
  db.session.commit()
  flash(f'{recipe.name} recipe deleted!','success')
  return redirect(url_for('.all_recipes'))

myspace/views/users.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, bcrypt, is_logged_in
from ..forms import RegisterForm, UpdateUserForm
from ..models import User

users = Blueprint('users', __name__)

# CREATE USER
@users.route("/new", methods=['GET', 'POST'])
@is_logged_in
def register():
  form = RegisterForm()
  users = User.query.all()
  curr_user = session['username']
  if form.validate_on_submit():
    hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email=form.email.data,
    password=hashed_pwd)
    db.session.add(user)
    db.session.commit()
    flash(f'Account created for {form.username.data}!', 'success')
    return redirect(url_for('.register'))
  return render_template('users/register.html', title="Register User", form=form, users=users, curr_user=curr_user)

# UPDATE USER
@users.route("/<int:user_id>/update", methods=['GET', 'POST'])
@is_logged_in
def update_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.username != session['username']:
    abort(403)
  form = UpdateUserForm()
  users = User.query.all()
  if form.validate_on_submit():
    session['username'] = form.username.data
    user.username = form.username.data
    user.email = form.email.data
    db.session.commit()
    flash(f'Account updated for {form.username.data}!','success')
    return redirect(url_for('.register'))
  elif request.method == 'GET':
    form.username.data = user.username
    form.email.data = user.email
  return render_template('users/update-user.html', title="Update User", form=form, users=users)

# DELETE USER
@users.route("/<int:user_id>/delete", methods=['POST'])
@is_logged_in
def delete_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.username != session['username']:
    abort(403)
  db.session.delete(user)
  db.session.commit()
  return redirect(url_for('main.logout'))

myspace/templates/about.html
{% extends 'layout.html' %}

{% block body %}
  
  <h1>About</h1>
  <p>This application is built on the Python Flask framework</p>

{% endblock body %}

myspace/templates/admin-dashboard.html
{% extends 'layout.html' %}

{% block body %}
  
  <p class="u-pull-right">Welcome back {{ session.username }}!</p>
  <h1>Admin Area</h1>

  <div class="row">

    <div class="one-third column">
      <div class="dashboard-item">
        <a href="{{ url_for('users.register')}}">
          <svg width="100" height="100">
            <circle cx="50" cy="27" r="25" stroke="green" stroke-width="4" fill="none" />
            <circle cx="50" cy="110" r="50" stroke="green" stroke-width="4" fill="none" />
          </svg>
        </a>
        <p>Manage Users</p>
      </div>
    </div>

    <div class="one-third column">
      <div class="dashboard-item">
        <a href="{{ url_for('blog.new_post')}}">
          <svg width="100" height="100">
            <line x1="20" y1="20" x2="80" y2="20" stroke="green" stroke-width="2" />
            <line x1="20" y1="40" x2="80" y2="40" stroke="green" stroke-width="2" />
            <line x1="20" y1="60" x2="60" y2="60" stroke="green" stroke-width="2" />
            <path d="M15,5 h70 a10,10 0 0 1 10,10 v55 h-15 a10,10 0 0 0 -10,10 v15 h-55 a10,10 0 0 1 -10,-10 v-70 a10,10 0 0 1 10,-10 z" stroke="green" stroke-width="4" fill="none" />
            <line x1="95" y1="71" x2="71" y2="95" stroke="green" stroke-width="4" />
          </svg>
        </a>
        <p>Manage Posts</p>
      </div>
    </div>

    <div class="one-third column">
      <div class="dashboard-item">
        <a href="{{ url_for('trackme.new_location')}}">
          <svg width="100" height="100">
            <circle cx="50" cy="50" r="45" stroke="green" stroke-width="4" fill="none" />
            <line x1="50" y1="5" x2="50" y2="12" stroke="green" stroke-width="2" />
            <line x1="50" y1="95" x2="50" y2="88" stroke="green" stroke-width="2" />
            <line x1="5" y1="50" x2="12" y2="50" stroke="green" stroke-width="2" />
            <line x1="95" y1="50" x2="88" y2="50" stroke="green" stroke-width="2" />
            <polygon points="45,45 75,25 55,55" stroke="green" stroke-width="2" fill="green" />
            <polyline points="45,45 25,75 55,55" stroke="green" stroke-width="2" fill="none" />
          </svg>
        </a>
        <p>Manage Locations</p>
      </div>
    </div>

  </div> 
  <!-- row ends here-->
  
  <div class="row">

    <div class="one-third column">
      <div class="dashboard-item">
        <a href="{{ url_for('recipes.new_recipe')}}">
          <svg width="100" height="100">
            <circle cx="50" cy="50" r="30" stroke="green" stroke-width="4" fill="none" />
            <circle cx="50" cy="50" r="20" stroke="green" stroke-width="2" fill="none" />
            <polygon points="5,80 10,80 10,50 5,50" stroke="green" stroke-width="2" fill="green" />
            <circle cx="7.5" cy="81" r="2.5" stroke="green" stroke-width="2" fill="green" />
            <line x1="7.50" y1="50" x2="7.5" y2="15" stroke="green" stroke-width="2" />
            <path d="M3,15 v15 A 2.5 2.5, 0, 0, 0, 12 30 v-15" stroke="green" stroke-width="2" fill="none" />
            <polygon points="95,80 90,80 90,50 95,50" stroke="green" stroke-width="2" fill="green" />
            <circle cx="92.5" cy="81" r="2.5" stroke="green" stroke-width="2" fill="green" />
            <path d="M90,50 Q90,15 95,15 L95,50" stroke="green" stroke-width="2" fill="none" />
          </svg>
        </a>
        <p>Manage Recipes</p>
      </div>
    </div>

  </div>
{% endblock body %}

myspace/templates/docs.html
{% extends 'layout.html' %}

{% block body %}
  
  <h1>About</h1>
  <p>This application is built on the Python Flask framework</p>

{% endblock body %}

myspace/templates/home.html
{% extends 'layout.html' %}

{% block body %}
  
<!-- Showcase -->
<section id="showcase">
  <h1>Giacomo's WebSpace</h1>
  <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab ipsum distinctio aut ad optio deleniti adipisci rem. Ut iure, voluptate, doloribus culpa ratione nulla tenetur hic earum temporibus, eos voluptatum?</p>
</section>
<!-- setup background image, 100vh and that's it -->

<!-- Portfolio -->
<section id="portfolio">

</section>

<!-- Contacts -->

<!-- Footer -->

{% endblock body %}

myspace/templates/landing-page.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Giacomo's Webspace</title>

  <!-- Fonts -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- Skeleton CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/skeleton.css') }}">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

</head>
<body>

  <div style="text-align: center; margin-top: 35vh;">
    <a href="{{ url_for('main.login')}}">
      <svg width="100" height="100" style="cursor: not-allowed;">
        <circle cx="50" cy="50" r="45" stroke="#ccc" stroke-width="2" fill="#eee" />
        <circle cx="50" cy="40" r="10" stroke="#ccc" stroke-width="1" fill="#ccc" />
        <path d="M50,40 L40,70 L60,70 z" stroke="#ccc" stroke-width="1" fill="#ccc" />
      </svg>
    </a>
    <h5>Welcome</h5>
  </div>

</body>
</html>

myspace/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Fonts -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- Skeleton CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/normalize.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/lib/skeleton.css') }}">

  <!-- Custom CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">

  <!-- Leaflet CSS for handling maps -->
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
   integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
   crossorigin=""/>

  <title>
    Giacomo's Webspace
    {% if title %}
       | {{ title }}
    {% endif %}
  </title>
  
</head>

<body>
  {% include 'includes/_navbar.html' %}

  <div class="container">
    {% include 'includes/_messages.html' %}

    {% block body %}
    {% endblock body %}
  </div>
  
  <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

myspace/templates/login.html
{% extends 'layout.html' %}

{% block body %}
  
<div style="width:40%; margin:auto; margin-top:5em">
  <h3>Admin Area</h3>

  <form method="POST" action="">
    <div>
      {{ form.username.label }}
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      {% endif %}
      {{ form.username(class_="u-full-width") }}
    </div>
    <div>
      {{ form.password.label }}
      {{ form.password(class_="u-full-width") }}
    </div>
    <div>
      {{ form.submit(class_="button-primary u-full-width") }}
    </div>
    {{ form.csrf_token }}
  </form>
</div>

{% endblock body %}

myspace/templates/sidebar-page.html
{% extends 'layout.html' %}

{% block body %}

  <div class="row">
    <div class="eight columns">
      
      {% block main %}
      {% endblock main %}

    </div>
    <div class="four columns">
      
      {% block sidebar %}
      {% endblock sidebar %}
    
    </div>
  </div>

{% endblock body %}