myspace/views/users.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, bcrypt, is_logged_in
from ..forms import RegisterForm, UpdateUserForm
from ..models import User

users = Blueprint('users', __name__)

# CREATE USER
@users.route("/new", methods=['GET', 'POST'])
@is_logged_in
def register():
  form = RegisterForm()
  users = User.query.all()
  curr_user = session['username']
  if form.validate_on_submit():
    hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
    user = User(username=form.username.data, email=form.email.data,
    password=hashed_pwd)
    db.session.add(user)
    db.session.commit()
    flash(f'Account created for {form.username.data}!', 'success')
    return redirect(url_for('.register'))
  return render_template('users/register.html', title="Register User", form=form, users=users, curr_user=curr_user)

# UPDATE USER
@users.route("/<int:user_id>/update", methods=['GET', 'POST'])
@is_logged_in
def update_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.username != session['username']:
    abort(403)
  form = UpdateUserForm()
  users = User.query.all()
  if form.validate_on_submit():
    session['username'] = form.username.data
    user.username = form.username.data
    user.email = form.email.data
    db.session.commit()
    flash(f'Account updated for {form.username.data}!','success')
    return redirect(url_for('.register'))
  elif request.method == 'GET':
    form.username.data = user.username
    form.email.data = user.email
  return render_template('users/update-user.html', title="Update User", form=form, users=users)

# DELETE USER
@users.route("/<int:user_id>/delete", methods=['POST'])
@is_logged_in
def delete_user(user_id):
  user = User.query.get_or_404(user_id)
  if user.username != session['username']:
    abort(403)
  db.session.delete(user)
  db.session.commit()
  return redirect(url_for('main.logout'))

myspace/templates/users/register.html
{% extends 'sidebar-page.html' %}

{% block main %}
  
  <h3>Add New User</h3>

  <form method="POST" action="">
    <div>
      {{ form.username.label }}
      {% if form.username.errors %}
        {% for error in form.username.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      {% endif %}
      {{ form.username(class_="u-full-width") }}
    </div>
    <div>
      {{ form.email.label }}
      {% if form.email.errors %}
        {% for error in form.email.errors %}
          <span>{{ error }}</span>
        {% endfor %}
      {% endif %}
      {{ form.email(placeholder="example@mailbox.com", class_="u-full-width") }}
    </div>
    <div>
      {{ form.password.label }}
      {{ form.password(class_="u-full-width") }}
    </div>
    <div>
        {{ form.confirm_password.label }}
        {% if form.confirm_password.errors %}
          {% for error in form.confirm_password.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% endif %}
        {{ form.confirm_password(class_="u-full-width") }}
    </div>
    <div>
      {{ form.submit(class_="button-primary") }}
    </div>
    {{ form.csrf_token }}
  </form>

{% endblock main%}

{% block sidebar %}

  <h3>Current Users</h3>

  <table class="u-full-width">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.username }}</td>
          <td>{{ user.email }}</td>
        </tr>
        {% if user.username == curr_user %}
        <tr>
          <td class="user-controls">
            <a href="{{ url_for('users.update_user', user_id=user.id) }}" class="button">Update</a>
          </td>
          <td class="user-controls">
            <form action="{{ url_for('users.delete_user', user_id=user.id) }}" method="POST">
              <input type="submit" value="delete" class="delete-btn">
            </form>
          </td>
        </tr>
        {% endif%}
      {% endfor %}
    </tbody>
  </table>

{% endblock sidebar %}

myspace/templates/users/update-user.html
{% extends 'layout.html' %}

{% block body %}
  <div style="width:40%; margin:auto;">
    <h3>Update User</h3>

    <form method="POST" action="">
      <div>
        {{ form.username.label }}
        {% if form.username.errors %}
          {% for error in form.username.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% endif %}
        {{ form.username(class_="u-full-width") }}
      </div>
      <div>
        {{ form.email.label }}
        {% if form.email.errors %}
          {% for error in form.email.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        {% endif %}
        {{ form.email(placeholder="example@mailbox.com", class_="u-full-width") }}
      </div>
      <div>
        {{ form.submit(class_="button-primary") }}
      </div>
      {{ form.csrf_token }}
    </form>
  </div>

{% endblock body%}