myspace/views/recipes.py
from flask import Blueprint, request, render_template, url_for, flash, redirect, session, abort

from .. import db, is_logged_in
from ..forms import RecipeForm
from ..models import Recipe

recipes = Blueprint('recipes', __name__)

# READ ALL RECIPES
@recipes.route("/", methods=['GET'])
def all_recipes():
  recipes = Recipe.query.order_by(Recipe.name).all()
  return render_template('recipes/recipe-book.html', title="My Recipes", recipes=recipes)

# READ ONE RECIPE
@recipes.route("/<string:name>")
def single_recipe(name):
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  return render_template('recipes/recipe-r.html', title=recipe.name, recipe=recipe)

# ADD NEW RECIPE
@recipes.route("/new", methods=['GET', 'POST'])
@is_logged_in
def new_recipe():
  recipes = Recipe.query.order_by(Recipe.name).all()
  form = RecipeForm()
  curr_user = session['username']
  if request.method =='POST':
    if form.validate_on_submit():
      recipe = Recipe(name=form.name.data, ingredients=form.ingredients.data, 
      steps=form.steps.data, stars=form.stars.data, user_name=curr_user)
      db.session.add(recipe)
      db.session.commit()
      flash(f'{form.name.data} recipe created!', 'success')
      return redirect(url_for('.all_recipes'))
    else:
        flash('Invalid Coordintes! Please try again', 'error')
  return render_template('recipes/recipe-cu.html', title="Create Recipe", form=form, curr_user=curr_user, recipes=recipes)

# UPDATE RECIPE
@recipes.route("/<string:name>/update", methods=['GET', 'POST'])
@is_logged_in
def update_recipe(name):
  recipes = Recipe.query.order_by(Recipe.name).all()
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  if recipe.user_name != session['username']:
    abort(403)
  form = RecipeForm()
  if request.method =='POST' and form.validate_on_submit():
    recipe.name = form.name.data
    recipe.ingredients = form.ingredients.data
    recipe.steps = form.steps.data
    recipe.stars = form.stars.data
    db.session.commit()
    flash(f'{form.name.data} recipe updated!','success')
    return redirect(url_for('.all_recipes'))
  elif request.method == 'GET':
    form.name.data = recipe.name
    form.ingredients.data = recipe.ingredients
    form.steps.data = recipe.steps
    form.stars.data = recipe.stars
  return render_template('recipes/recipe-cu.html', title="Update Recipe", form=form, recipes=recipes)

# DELETE RECIPE
@recipes.route("/<string:name>/delete", methods=['POST'])
@is_logged_in
def delete_recipe(name):
  recipe = Recipe.query.filter_by(name=name).first_or_404()
  if recipe.user_name != session['username']:
    abort(403)
  db.session.delete(recipe)
  db.session.commit()
  flash(f'{recipe.name} recipe deleted!','success')
  return redirect(url_for('.all_recipes'))

myspace/templates/recipes/recipe-book.html
{% extends 'layout.html' %}

{% block body %}
  
  <h1>Welcome to my Blog!</h1>

  <div id="blogroll">
    {% for recipe in recipes %}
    <article>
      <div class="card">
        <h4><a href="{{ url_for('recipes.single_recipe', name=recipe.name) }}">{{ recipe.name }}</a></h4>
        <div>
          <small>{{ recipe.stars }}</small>
        </div>
      </div>
    </article>

    <hr>
    {% endfor %}
  </div>
  

{% endblock body %}

myspace/templates/recipes/recipe-cu.html
{% extends 'sidebar-page.html' %}

{% block main %}

<h3>{{ title }}</h3>

<form method="POST" action="">
  <div>
    {{ form.name.label }}
    {% if form.name.errors %}
      {% for error in form.name.errors %}
        <span>{{ error }}</span>
      {% endfor %}
    {% endif %}
    {{ form.name(class_="u-full-width") }}
  </div>
  <div>
    {{ form.ingredients.label }}
    {{ form.ingredients(class_="u-full-width") }}
  </div>
  <div>
    {{ form.steps.label }}
    {{ form.steps(class_="u-full-width") }}
  </div>
  <div>
    {{ form.stars.label }}
    {{ form.stars(class_="u-full-width") }}
  </div>
  <div>
    {{ form.submit(class_="button-primary") }}
  </div>
  {{ form.csrf_token }}
</form>

{% endblock main %}

{% block sidebar %}

  <h3>Recent Recipes</h3>

  {% if recipes %}
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Recipe</th>
        <th>Author</th>
      </tr>
    </thead>
    <tbody>
      {% for recipe in recipes %}
      <tr>
        <td><a href="{{ url_for('recipes.single_recipe', name=recipe.name) }}">{{ recipe.name }}</a></td>
        <td>{{ recipe.user_name }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
    <p>You haven't written any recipes yet!</p>
  {% endif %}

{% endblock sidebar %}

myspace/templates/recipes/recipe-r.html
{% extends 'layout.html' %}

{% block body %}
  
  <article id="post">
    <div>
      <div id="post-header">
        <div>
          <h3>{{ recipe.name }}</h3>
          <small><em>Written by {{ recipe.user_name }} | {{ recipe.stars }}</em></small>
        </div>
        
      </div>
      <div class="post-contents">
        <p>{{ recipe.ingredients }}</p>
      </div>

      <div class="post-contents">
        <p>{{ recipe.steps }}</p>
      </div>
    </div>
    <hr>
    {% if recipe.user_name == session['username'] %}
    <div class="post-controls">
      <a href="{{ url_for('recipes.update_recipe', name=recipe.name) }}" class="button">Update</a>
      <form action="{{ url_for('recipes.delete_recipe', name=recipe.name) }}" method="POST">
        <input type="submit" value="delete" class="delete-btn">
      </form>
    </div>
    {% endif %}   
  </article>

{% endblock body %}